name: CI/CD Pipeline
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/goqik-app:latest

      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          script: |
            set -e
            echo "[deploy] pulling image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/goqik-app:latest

            echo "[deploy] stop & remove old container..."
            docker stop goqik-app 2>/dev/null || true
            docker rm goqik-app 2>/dev/null || true

            echo "[deploy] start new container..."
            docker run -d --restart always --name goqik-app \
              -p 3000:3000 \
              -e DATABASE_URL="postgresql://postgres.weceveojlzykpjbfblsh:[@Wangzb805903]@aws-1-us-east-2.pooler.supabase.com:6543/postgres" \
              ${{ secrets.DOCKERHUB_USERNAME }}/goqik-app:latest

            echo "[deploy] wait app warm up..."
            sleep 8

            echo "[deploy] server-side health check..."
            docker ps -a
