name: Deploy GoQik (SSOT via Secrets)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  APP_DIR: /root/goqik
  PORT: 8080
  NODE_VERSION: 18

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install & Build (optional)
        run: |
          npm ci
          npm run build || true

      - name: Upload workspace to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: .
          target: ${{ env.APP_DIR }}
          rm: true
          overwrite: true
          strip_components: 0
          timeout: 180s

      - name: Remote deploy & health check
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            set -euo pipefail
            APPDIR="${APP_DIR}"
            cd "$APPDIR"

            if ! command -v pm2 >/dev/null 2>&1; then
              npm i -g pm2
            fi

            if [ ! -d node_modules ]; then
              npm ci --omit=dev || npm i --omit=dev
            fi

            cat > "$APPDIR/.env" <<ENV
PORT=${PORT}
NODE_ENV=production
DATABASE_URL=${{ secrets.DATABASE_URL }}
ENV
            chmod 600 "$APPDIR/.env"

            if [ -f ecosystem.config.js ] || compgen -G "ecosystem.config.*" > /dev/null; then
              pm2 start ecosystem.config.* --only goqik 2>/dev/null || true
              pm2 restart goqik --update-env || true
            elif [ -f src/index.js ]; then
              pm2 describe goqik >/dev/null 2>&1 \
                && pm2 restart goqik --update-env \
                || pm2 start src/index.js --name goqik --update-env
            else
              echo "[!] src/index.js 或 ecosystem.config.* 未找到"; exit 2
            fi

            pm2 save || true

            for i in {1..30}; do
              curl -fsS "http://127.0.0.1:${PORT}/readyz" && echo "READY" && exit 0 || sleep 2
            done

            echo "[!] Backend not ready; recent logs:"
            pm2 logs --lines 150 goqik
            exit 1
